### ISSUE TITLE
Can't confirm account

### ISSUE THREAD

**Issue by goffchris** [backface/turtlestitch#136] opened 2024-10-20 12:55 UTC
I attempted to register an account, but have not been able to confirm. I did not receive a confirmation email, but if I try to register the account I get an "account already exists" message. I seem to be stuck.

**Comment by chmod4711** [comment] 2024-10-20 13:56
Hi! I've confirmed your account. Thanks for reporting the problem. I'll check all the mail relevant settings in order to get the problem solved.

**Comment by backface** [comment] 2024-11-10 13:21
closing since this case is solved and the platform moved to a new codebase

**Closed by backface** 2024-11-10 13:21 UTC
